#pragma once

template <class T>
class CProxy_IOEControlEvents : public IConnectionPointImpl<T, &__uuidof(_IOEControlEvents), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
