#pragma once

template <class T>
class CProxy_IOEGOfficeEvents : public IConnectionPointImpl<T, &__uuidof(_IOEGOfficeEvents), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
