#pragma once

template <class T>
class CProxy_IOELauncherEvents : public IConnectionPointImpl<T, &__uuidof( _IOELauncherEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
